export{default as Home} from './Home'
export{default as About} from './About'
export{default as Contact} from './Contact'
export{default as Signup} from './Signup'
export{default as Nopage} from './Nopage'
